### ISSUE TITLE
We've got possible candidates ready to take over the maintenance of your list

### ISSUE THREAD

**Issue by DandelionSprout** [EasyList-Lithuania/easylist_lithuania#10]
Hello. The EasyList community has heard your call for help in https://forums.lanik.us/viewtopic.php?f=101&t=45003, and I presume I am able to tell that (to the degree I've understood the situation) there are two candidates who feel they can take over and resume your list: Me, and @LanikSJ.

Neither me or him have done the needed preparations for a full takeover *just yet* (In my case we'd be talking perhaps 3 more weeks), but I feel we are already able to take care of hotfixes and ABP userform reports and such things, presuming either or both of us (Preferably both, as it currently stands) were given maintainer privileges in this repo.

**Comment by gymka** [comment]
Invited both

**Comment by krystian3w** [comment]
For users, it would be better to avoid manually updating the link, and under the old one you can see newer filters.

you could probably even change the name of the organization and repository to:

> `EasyList-Lithuania-and-Serbo-Croatian /easylist_lithuania_Serbo-Croatian`

**Comment by DandelionSprout** [comment]
I've put the plans to expand EasyList Lithuania's geographic scope indefinitely, since it hinged on me being the sole maintainer of a list that was fully rewritten from scratch, and which'd be in a different repo.

I did a 180° when I saw that the easiest option was to instead do basic summer cleaning of the existing Lithuanian list instead.

**Comment by DandelionSprout** [comment]
As it has been reasonably established by now that gymka has indeed ceased working on this project, and that I've done occasional maintenance roughly monthly, it seems safe to say that this issue has been resolved now.
