### ISSUE TITLE
Missing pictures on domoplius.lt

### ISSUE THREAD

**Issue by KrisGalcz** [EasyList-Lithuania/easylist_lithuania#11]
Hey, there are missing pictures on [https://domoplius.lt/](https://domoplius.lt/)
**How to reproduce**
Go to [https://domoplius.lt/](https://domoplius.lt/) with EL Lithuania
On the main website scroll down. Pictures under "NT naujienos" are missing
**Proposed filter**
`@@||static.plius.lt/plius/images/articles/$image,domain=domoplius.lt`

**Comment by DandelionSprout** [comment]
My apologies for not noticing this report sooner. I thought I'd automatically receive E-mails about reports after I joined the team for EasyList Lithuania, which turned out to not be the case by default.

**Comment by KrisGalcz** [comment]
No worries:) Thanks for the fix:)
