### ISSUE TITLE
broken site

### ISSUE THREAD

**Issue by iibett** [EasyList-Lithuania/easylist_lithuania#14]
AdGuard Annoyances brake chat "Pradėti pokalbį" function [on this website ](https://www.telia.lt/privatiems/pagalba/gyvai) need to white list `@@||secure.livechatinc.com^$subdocument,domain=www.telia.lt`

**Comment by DandelionSprout** [comment]
A tempfix has now added to EasyList Lithuania, which I can hopefully submit upstream to AdGuard Filters within a couple days. Thanks.
