### ISSUE TITLE
skelbiu.lt and 15min.lt

### ISSUE THREAD

**Issue by iibett** [EasyList-Lithuania/easylist_lithuania#15]
sponsored links on skelbiu.lt
`skelbiu.lt##li.kainos-item`
<img width="894" alt="sponsored" src="https://user-images.githubusercontent.com/87672930/134333266-491d88b3-ee64-4500-b3df-3337b88808fd.PNG">

ad for a loan also on skelbiu.lt [example](https://www.skelbiu.lt/skelbimai/zaidimu-kompiuteris-hp-omen-57413119.html)
`skelbiu.lt###bigbank-small-loan`
<img width="713" alt="loan" src="https://user-images.githubusercontent.com/87672930/134333702-368a2726-04a8-493d-b867-ff3587496970.PNG">
ads on 15min.lt and ad placeholders
`15min.lt##.xml-items-list`
`15min.lt##div.front-block.row-24:nth-of-type(18)`
<img width="677" alt="ad" src="https://user-images.githubusercontent.com/87672930/134335401-25dc816b-cb1c-443e-ac39-1e9c96f37cee.PNG">

**Comment by DandelionSprout** [comment]
I have now added fix-entries for `skelbiu`.

For `15min.lt`, the ad in the screenshot is already supposed to be blocked by `15min.lt#?#.item:-abp-has(> a[href*="//bit.ly"][target="_blank"] > img)`. I did however find a few other ads that only affected ABP (and not uBO), which I've blocked now.

**Comment by iibett** [comment]
@DandelionSprout 
`15min.lt#?#.item:-abp-has(> a[href*="//bit.ly"][target="_blank"] > img)` doesn't work because **naujienos** sections where I saw ads doesnt use `.item` it uses  `.post-item` . Add `15min.lt##.field_banner_desktop` to block those ads

Also in skelbiu.lt you didn't block sponsored links ` skelbiu.lt##li.kainos-item` they are shown in my firs image.
Thanks.

**Comment by DandelionSprout** [comment]
It took me some time to find an example webpage for `skelbiu.lt##li.kainos-item`, but I've found it now and will add it.

Although I can't reproduce the need for `15min.lt##.field_banner_desktop` when using uBlock Origin in Chrome, I'll add that entry too. Thanks again.
