### ISSUE TITLE
PiHole Reports Sites Separated by Commas as Invalid

### ISSUE THREAD

**Issue by KaiserCalm** [EasyList-Lithuania/easylist_lithuania#18]
Output after block list update:
  [i] Target: https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 587 domains, 96 domains invalid!
      Sample of invalid domains:
      - 2.0]
      - aciu.lt,gydomasismasazas.lt
      - alio.lt,alio.proxy.dlf.lt
      - anglija.lt,kamane.lt
      - avitela.lt,elektromarkt.lt
  I'm not sure if this is your issue, however I wanted to report it anyway.

**Comment by DandelionSprout** [comment]
With no apparent further developments in this situation, I'll declare this a solved case now. Comments will remain open.

**Comment by DandelionSprout** [comment]
Oh, right, I forgot I was supposed to make a raw-domains version of this list. I'll reopen it for a short while.

**Comment by DandelionSprout** [comment]
Fixed by https://github.com/EasyList-Lithuania/easylist_lithuania/commit/3b7efbf6e74e18772e557b87bab9982684e09196

**Comment by iibett** [comment]
In the host file filter list you wrote some domains with and without `www.` in the the same line, is there any particular reason you did this because I've never seen host file filter list written like this.
@DandelionSprout

**Comment by DandelionSprout** [comment]
Although the technique is very rarely used by others than me, I know of at least 2 other lists that use it independently of me:

* https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/NoFormatting/optimized-win.hosts
* https://raw.githubusercontent.com/lewisje/jansal/master/adblock/hosts

The technique is recognised by AdGuard Home, at the very least; and seemingly also by OS hosts files.
