### ISSUE TITLE
15min not works anymore?

### ISSUE THREAD

**Issue by anzi** [EasyList-Lithuania/easylist_lithuania#2]
seems on article regular filter not works, but possible block if selected elements are:

> ||video1.15min.lt/15min_video/2016/05/574dacaca0104_480p.mp4
> ||15min.lt/assets/images/bg/s.gif

if selected only 
> ||15min.lt/assets/images/bg/s.gif

then another issue pops-up, but then block not helps:

> 15min.lt###adblock-content
> 15min.lt###adblock-content.active

**Comment by gymka** [comment]
kokiam čia url neveikia? jau senai viskas sutvarkyta... praeitą savaitę buvo skundas dėl 15min, bet ten žmogus naudojo ir kitą filtrą kuris ir kėlė bėdas(aš nesivarginsiu tvarkyt kitų filtrų bėdų). easylist+easylist lithuania=jokių bėdų 15min.lt
http://www.15min.lt/kaip-isjungti-reklamos-blokavima 
5 iš 6 žali, paskutinis nekelia bėdų

**Comment by anzi** [comment]
negaliu skaityti nieko pvz http://www.15min.lt/verslas/naujiena/bendroves/teismus-pries-vmvt-laimejes-verslininkas-cia-taikomi-dvigubi-standartai-663-668079

**Comment by gymka** [comment]
palikit įjungtus filtrus „easylist“ ir „easylist lithuania“ tada žiūrėkit:) geriau kai pranešama per naršyklę, tada aš matau koki filtrai naudojami, kada atnaujinti, kokia naršyklė, etc. galiu pats paimt ir pabandyt su ta pačia naršykle ir filtrais
2016-08-17 19:05, anzi rašė:

**Comment by anzi** [comment]
adblock ant chrome nerandu tokios funkcijos, naudojami:
×   Enabled Adblock Warning Removal List Last updated at 08:10:38 today
×   Enabled EasyList Last updated at 18:08:00 on 14/08/2016
×   Enabled RuAdList+EasyList Last updated at 18:08:00 on 14/08/2016
×   Enabled EasyList Lithuania+EasyList Last updated at 18:08:00 on 14/08/2016
[_] Allow some non-intrusive advertising

**Comment by gymka** [comment]
problema buvo tik su chrome(aš naudoju firefox), problema išspręsta. kita problema jog chrome siūlo tik „easylist easylist lithuania“, o ne juos atskirai... dabar teks laukt dieną ar dvi kol bus atnaujintas „easylist lithuania“:D siūlyčiau pašalint tą filtrą ir pridėt atskirai tik mano(easylist jau yra, tai truksta tik lt dalies) http://margevicius.lt/easylistlithuania.txt
2016-08-17 19:11, anzi rašė:

**Comment by anzi** [comment]
tarsi super, dėkui
