### ISSUE TITLE
delfi.lt

### ISSUE THREAD

**Issue by iibett** [EasyList-Lithuania/easylist_lithuania#20]
Change this `torrent.ai,torrent.lt##div.block:nth-of-type(3)` to `torrent.ai,torrent.lt###inside div.block:nth-of-type(3)` because some false positives occur.
and I found a placeholder on delfi.lt

`m.delfi.lt###mdelfi_latest_news:style(min-height: unset !important)`
[example.](https://i.imgur.com/lh2U4Jt.png)
It would be nice if you could add me to the GitHub repo so I wouldn't have to make a new issue every time I find a problem.

**Comment by iibett** [comment]
Thanks, but I still can't add new commits did you give me the editing rights?

@DandelionSprout

**Comment by DandelionSprout** [comment]
I at least think I've given you edit rights now. Thanks for the headsup.
