### ISSUE TITLE
Ads at https://www.delfi.lt/

### ISSUE THREAD

**Issue by edivaniadc** [EasyList-Lithuania/easylist_lithuania#21]
Can you please block some ads at https://www.delfi.lt/

Simply search for `dcdn.lt/images/hntis/` 
OR 1 by 1:
* top banner ([class^="hero samsung"])
* right rail (.samsung)
* lower right rail (.login)
* below the article. (.ad mb20 - inline script: _dlf.adxtag(928806)

Suggested filters: 
`||dcdn.lt/images/hntis/$third-party,domain=delfi.lt`
`delfi.lt###header-top-banner`
<img width="832" alt="delfi" src="https://user-images.githubusercontent.com/57706597/162741077-71a579ef-7d18-433d-a566-aaa960511d5d.png">

**Comment by edivaniadc** [comment]
> I can't reproduce the ads. what ad-blocker are you running? did you update filters?

Hi @iibett thanks for your reply. I'm using Adblock Plus with filter lists: [ABP filters](https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt) + [Easy List Lithuanian](https://easylist-downloads.adblockplus.org/easylistlithuania+easylist.txt)
VPN location: Lithuania 
_Filter lists are up to date._

**Comment by DandelionSprout** [comment]
Delfi is known to defeat ABP's syntax support fairly easily, so this issue could presumably also be reported to https://github.com/abp-filters/abp-filters-anti-cv

**Comment by DandelionSprout** [comment]
Okay, so to my honest surprise, the ads can be removed by simply copying over `@@||adform.net/banners/scripts/adx.js|$script,domain=delfi.lt` from RU AdList.

**Comment by edivaniadc** [comment]
Hi @DandelionSprout and/or @iibett it looks like `@@||adform.net/banners/scripts/adx.js|$script,domain=delfi.lt` added on [commit](https://github.com/EasyList-Lithuania/easylist_lithuania/commit/2d85064d635470db16caf7c73d83bf4524206c4b) is no longer fixing these ads. 

May I ask you to check please if suggested filters work for you?
`||dcdn.lt/images/hntis/$third-party,domain=delfi.lt`
`delfi.lt###header-top-banner`

Thanks in advance.

**Comment by iibett** [comment]
Can I ask you why you don't want to switch to ublock origin? You won't have to deal with these problems.

**Comment by edivaniadc** [comment]
> Can I ask you why you don't want to switch to ublock origin? You won't have to deal with these problems.

I appreciate your advice, but what I'm trying to suggest here is a solution for other ad blocker users as well.

**Comment by DandelionSprout** [comment]
EasyList Lithuania has for many years been included in ABP, so we've got little choice than to at least attempt to added fixes that work for ABP and AdBlock as well.

**Comment by iibett** [comment]
I'm not saying we shouldn't, I'm just encouraging people to use a better ad blocker @DandelionSprout

**Comment by edivaniadc** [comment]
@iibett @DandelionSprout can you please check if fixes https://github.com/EasyList-Lithuania/easylist_lithuania/commit/b14ba0d work for you on ABP? 

The ones that work for me is still:
`||dcdn.lt/images/hntis/$third-party,domain=delfi.lt`
`delfi.lt###header-top-banner`

**Comment by DandelionSprout** [comment]
On analysis, those two entries seem to work as intended to remove the ads, and I'll add them now; although it worries me that I seem to be unable to remove the resulting placeholder near the top in ABP no matter how many varieties of `delfi.lt##.hero` I try to use.
