### ISSUE TITLE
Blocks entire pigu.lt website

### ISSUE THREAD

**Issue by linaspurinis** [EasyList-Lithuania/easylist_lithuania#22]
Blocks entire pigu.lt website, cannot open login anything. Safari on Mac.

**Comment by iibett** [comment]
Are you using a dns based ad blocker?

**Comment by linaspurinis** [comment]
Yes, https://my.nextdns.io/ 
They have EasyList Lithuania in selectable blocklist.

**Comment by iibett** [comment]
It should be fixed now wait couple hours until they update their filter list.

**Comment by DandelionSprout** [comment]
I have very little experience with NextDNS (instead preferring to use AdGuard Home), though they do work pretty similarly. Since the reason for `pigu.lt`'s blocking has long since been forgot, I approve of the removal of that entry.
