### ISSUE TITLE
Ads on `delfi.lt`

### ISSUE THREAD

**Issue by eporubin** [EasyList-Lithuania/easylist_lithuania#23]
Hi, I came across this ads on `m.delfi.lt` and would suggest the addition of the following filters:

- Ads at the bottom of [the article](https://m.delfi.lt/uzsienyje/article.php?id=92436525) `delfi.lt###top-pt`
![image](https://user-images.githubusercontent.com/33602691/216588233-4e041070-ba02-468b-917a-3559fc25611d.png)

- Ads at the bottom of the page popping up `delfi.lt##.sevenbet-juosta`
![image](https://user-images.githubusercontent.com/33602691/216588439-c8957af7-41a9-4e20-8447-4bbf2fc9eb99.png)

- Ads embedded on the page from Samsung `delfi.lt##.samsung`
![image](https://user-images.githubusercontent.com/33602691/216588832-daf60a08-fe79-4771-af55-770e006d2c83.png)

Thank you in advance for looking into it.

**Comment by DandelionSprout** [comment]
Which adblocker are you using? My understanding is that uBlock Origin and AdGuard receives much fewer of these ads on-average due to being able to use various scripts, while Adblock Plus and AdBlock has a harder time removing those ads but can be attempted to some degree.

**Comment by eporubin** [comment]
sorry I forgot to mention I am using ABP for Chrome extension with ABP Filters + Easylist +Lithuania List

**Comment by DandelionSprout** [comment]
Duly noted. I'll try to look into it tonight or tomorrow.

**Comment by iibett** [comment]
I fixed the Samsung and 7bet ads. Samsung ads are injected with JavaScript so it's hard to block them without using scriptlets and I don't know what to do with the paid articles should they be blocked? They don't seem like "normal ads" @DandelionSprout what do you think?
 **I highly recommend using uBlock Origin for a more efficient ad-blocking.**

**Comment by DandelionSprout** [comment]
I have precedence from my work on "Nordic Filters" of blocking paid articles if they have no journalistic merit, e.g. "Buy this new phone for reasons that the phone manufacturer told us to mention".

**Comment by CbumDino** [comment]
Hey @DandelionSprout @iibett I can see banners at https://www.delfi.lt/uzsakomasis-turinys/premium/nuo-dirbtinio-intelekto-iki-gresmiu-skaitmenineje-erdveje-vilniuje-ekspertai-ieskos-atsakymu-i-interneto-keliamus-issukius-120024687
<img width="1512" alt="Screenshot 2024-06-04 at 14 54 01" src="https://github.com/EasyList-Lithuania/easylist_lithuania/assets/65717387/51924ace-c422-4042-8779-4fdd06294bc9">

using the same setup mentioned before (ABP for Chrome extension with ABP Filters + Easylist +Lithuania List)

This would do the job without leaving placeholders - `delfi.lt##[style*="g.delfi.lt/images/ccc/"]`

Thank you in advance,

**Comment by DandelionSprout** [comment]
• Which browser are you using?
• Are you using Adblock Plus version 3.x or 4.x?

**Comment by CbumDino** [comment]
> Are you using Adblock Plus version 3.x or 4.x?

Hey @DandelionSprout Version 4.x.

**Comment by DandelionSprout** [comment]
Ouch.

So, 4.x is when Adblock Plus decided to go all-in on *supporting* the rightfully feared Manifest V3, so I expect very large amounts of ads that haven't blocked yet.

And even if I had spent a fair bit of time to block the ads in the screenshot, or even to simply add the suggested entry to the list, what'd be the point of it all if I couldn't even tell how many days or potentially weeks it'd take before ABP would apply that new entry, or even if the time delay would be so long that Delfi would've come up with new strategies in the meantime.

For me personally, ABP 4.x is **far** off-limits for me to ever support (except on Firefox). I can't however speak for anyone else who have any connections to EasyList Lithuania, I admit.

**Comment by CbumDino** [comment]
Hey @DandelionSprout, 

MV3 is so far only used in chrome, anyway i'm able to reproduce it on FF as well. 
Are you able to reproduce it as well ? 

Thank you once again.

**Comment by DandelionSprout** [comment]
Hmm, good to know it's a problem in FF too. I'll take a look into it within 16〜48hrs.

**Comment by monzta** [comment]
> And even if I had spent a fair bit of time to block the ads in the screenshot, or even to simply add the suggested entry to the list, what'd be the point of it all if I couldn't even tell how many days or potentially weeks it'd take before ABP would apply that new entry, or even if the time delay would be so long that Delfi would've come up with new strategies in the meantime.

In the best case it will not take days or weeks for filter list updates to reach the users. I checked [the page](https://www.delfi.lt/uzsakomasis-turinys/premium/nuo-dirbtinio-intelekto-iki-gresmiu-skaitmenineje-erdveje-vilniuje-ekspertai-ieskos-atsakymu-i-interneto-keliamus-issukius-120024687) with ABP 4.1 in Chrome with your list and the ads are gone.

In ABP the dynamic filter limit in MV3 is used to provide diff updates of all default filter lists. That means that changes done to these lists will reach the user even without a full extension update. Right now the idea is to have an extension release every 2 weeks that only contains a static filter list update. Then between those 2 weeks users will get the filter list changes via the mentioned diff updating system.

Maye this could be even improved now that the Chrome Web Store [allows much faster reviews when the only change is updating the static filter lists](https://developer.chrome.com/blog/extensions-skip-review-eligible-changes).

**Comment by DandelionSprout** [comment]
I remember I was more than a little concerned due to version date differences between https://easylist-downloads.adblockplus.org/v3/full/dandelion_sprouts_nordic_filters+easylist.txt and https://easylist-downloads.adblockplus.org/dandelion_sprouts_nordic_filters+easylist.txt; the former lagging a week behind the latter as far as the version dates alone went, when I first learnt of the `/v3/full/` list versions around 25th of May.

However, you seem to be the expert on those matters, so I take your words for all of that. I've been explained the delta system in passing, though there were certainly concerns at the time I was explained about it (approx. June-July 2023) whether the delta would get overloaded between ABP updates or not.
