### ISSUE TITLE
[SOLVED] LNKGO Outsource Ad Server? (with URL of ad)

### ISSUE THREAD

**Issue by dariusworks** [EasyList-Lithuania/easylist_lithuania#3]
URL I cough
http://lt.adocean.pl/files/x/uef/penesyy/rchhlpqsil/10s1.mp4
http://lt.adocean.pl/files/x/lko/fhumjdb/xajkevmjdv/1.mp4
http://lt.adocean.pl/ad.xml?id=B7imjetS8pWUtKUK85LEnzVDP0r9xe82SQ03MoZv_E7.E7/prespots=3/midspots=0/postspots=0/overspots=0
I think that can be helpful

**Comment by gymka** [comment]
Labas, dėkui jog padedi. Didžiausia problema jog aš neturiu laiko :) žmogus praneša apie problemą(laišką gaunu kartą per savaitę su visais pranešimais padarytais tą savaitę) ir tada daugmaž peržiūriu kažką patikrinu, kažkur ignore. Tada jei turiu laiko ir galima greit pataisyt tai pataisau, kam neturiu laiko tas lieka vėlesniam laikui ir savaime aišku ne viskam ateina tas vėlesnis laikas. lnk ir tv3 saugyklas žiūriu per tvbox, o ne kompe tai ir nematau jog ten yra reklamų :D

tldr;
pataisiau

**Comment by gymka** [comment]
linux+firefox=viskas gerai jokių reklamų
windows+firefox=išvis nerodo, net ir išjungus adblock
windows+chrome=rodo reklamą...
