### ISSUE TITLE
[Solved] neblokuoja delfi sitehat, left, right, ir apačios

### ISSUE THREAD

**Issue by andzi** [EasyList-Lithuania/easylist_lithuania#4]
kažkodėl chrome nesuveikia blokas pridėjus (nors šios taisyklės jau yra?) :
delfi.lt###wallpaper-sitehat
delfi.lt###wallpaper-link-left
delfi.lt###wallpaper-link-right

**Comment by gymka** [comment]
Vienu metu buvo problema jog sąrašą atnaujinau iš windows ir perrašė eilučių pabaigas, bet po kelių dienų pastebėjau ir ištaisiau. Pažiūrėkite ar sąraše rodo atnaujinimo datą 07.16. Šita bėda pataisyta.

**Comment by gymka** [comment]
jo problema tikrai yra, pastoviai visos problemos su chrome...

**Comment by gymka** [comment]
Delfi surado chrome+adb spragą :D ir naudojasi good 4 u, aš naudoju firefox. Tai chrome naudotojams galiu pasiūlyt: įsirašykit normalią naršyklę, o ne tą kurios kūrėjai ir taip apie jus žino daugiau nei jūs norėtumėte. Net nesiruošiu gilintis ir perrašinėt filtrų. 
Jei vistiek norit naudot chrome, įdiekit tampermonkey ir scenarijų https://greasyfork.org/en/scripts/14720-it-s-not-important
Tai yra chrome bėda, ne adb ir ne „easylist lithuania“.
Jei kam(puslapių savininkams kurių puslapiuose yra reklamų) įdomu tai už minimalų mokestį galiu pasidalint detalėmis :D
