### ISSUE TITLE
delfi.lt

### ISSUE THREAD

**Issue by krystian3w** [EasyList-Lithuania/easylist_lithuania#6]
`delfi.lt#?##header-top-banner + [class]:-abp-has(img[src*="cdn"])`

![obraz](https://user-images.githubusercontent.com/35370833/53839505-e9678d00-3f97-11e9-99ce-8bc822b98e35.png) |
--- |

Self promotion?

https://www.reddit.com/r/uBlockOrigin/comments/axk2kp/blocking_using_wildcards/

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12354

**Comment by krystian3w** [comment]
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#pre-parsing-directives possible add or blocked by Eyeo / Adblock Plus Company?

**Comment by gymka** [comment]
issue solved with commit https://github.com/abp-filters/abp-filters-anti-cv/commit/bd2e6be67a06fd39b92308ea98dcc5c6d431d774

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/41420
https://github.com/uBlockOrigin/uAssets/issues/6372
https://github.com/abp-filters/abp-filters-anti-cv/issues/57
