### ISSUE TITLE
wrong filter and dead address 

### ISSUE THREAD

**Issue by mapx-** [EasyList-Lithuania/easylist_lithuania#7]
wrong filter (reported here: https://forums.lanik.us/viewtopic.php?f=101&t=43512 )
`@@||googlesyndication.com/pagead/$third-party`

You should also correct the list address from dead domain ( Homepage: http://margevicius.lt/easylist_lithuania/ )  to github one

**Comment by gymka** [comment]
1. Domain not dead, simply deleted WordPress so http://margevicius.lt/easylistlithuania.txt works as intended :)
2. I'll check other issue

**Comment by mapx-** [comment]
- going to http://margevicius.lt/easylist_lithuania/ you'll get a 404 error. 
Add the complete address eventually: http://margevicius.lt/easylistlithuania.txt

- it's very wrong: you are whitelisting all `googlesyndication.com/pagead` scripts. IT should be done only for speicific domains.

**Comment by gymka** [comment]
that rule was intended for telikaz.biz https://github.com/EasyList-Lithuania/easylist_lithuania/commit/13b6408dafbaeb31d6bdaeb89cb3c837bf4d47a7 , that site no longer exists, so i remove that rule.
