### ISSUE TITLE
SSL cert failing

### ISSUE THREAD

**Issue by ryanbr** [EasyList-Lithuania/easylist_lithuania#8]
Hey, we're getting reports of the SSL cert errors for https://margevicius.lt/easylistlithuania.txt

```
Your connection is not private
Attackers might be trying to steal your information from margevicius.lt (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

https://www.ssllabs.com/ssltest/analyze.html?d=margevicius.lt

**Comment by garas** [comment]
@gymka It looks like website/blog was closed, so maybe update links to point directly to GitHub.

URLs at https://github.com/gorhill/uBlock/blob/master/assets/assets.json could be updated to


- contentURL: https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt

- supportURL: https://www.facebook.com/easylistlithuania/ or https://github.com/EasyList-Lithuania/easylist_lithuania

**Comment by gymka** [comment]
Whats the point? Domain belongs to me, host belongs to me. I don't have time to play with site, site was in lithuanian and had no rellation to easylist or adblock, so nothing changes. I use host only as my private space in www so i could share files.

**Comment by gymka** [comment]
Fixed ssl issue
