### ISSUE TITLE
Fix Certificate error

### ISSUE THREAD

**Issue by jabonsolo** [EasyList-Lithuania/easylist_lithuania#9]
Hello, 

I don't know if this is the right place to report it. Is there something going on on margevicious.lt? Link to the list ([https://margevicius.lt/easylistlithuania.txt](https://margevicius.lt/easylistlithuania.txt)) shows an outdated security certificate, but also when accepting the risk and trying to access it there is a request not found. 

Are you aware of it? Do you know if there is a date on when this could be fixed as I'm not able to add list to ABP due to this problem.

**Comment by garas** [comment]
You can use https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt instead.

But EasyList Lithuania is not maintained anymore, and new advertisements are not blocked anymore.

https://github.com/EasyList-Lithuania/easylist_lithuania/issues/8
